import Head from "next/head";
import { Logo } from "@/components/svgs/logo";
export default function Home() {
    return (
        <>
            <Head>
                <title>Insightful</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav className="w-screen">
                <div className="w-full h-14 bg-gray-200"></div>
            </nav>
            <main className="">
                <section id="hero" className="text-center bg-mainpink">
                    <div className="flex justify-between items-center p-6 bg-mainpink">
                        <div className="flex gap-3 items-center text-xl font-title text-mainred">
                            <Logo className="w-9 h-9" />
                            <h1>Insightful</h1>
                        </div>
                        <div className="flex gap-4">
                            <button className="py-1 px-5 text-sm font-bold uppercase rounded-full border border-mainred text-mainred">
                                Login
                            </button>
                            <button className="py-1 px-5 text-sm font-bold text-white uppercase rounded-full bg-mainred">
                                Signup
                            </button>
                        </div>
                    </div>
                    <div className="flex flex-col items-center py-12">
                        <h1 className="w-3/4 leading-10 font-title text-[40px] text-mainred max-w-[1123px]">
                            A career mentorship platform designed for the women and
                            gender-diverse community.
                        </h1>
                        <h2 className="mt-2 w-2/3 font-medium text-[28px] max-w-[1000px]">
                            Lorem ipsum dolor sit amet consectetur. Orci dignissim amet semper
                            mauris felis nam. Risus.
                        </h2>
                        <div className="flex gap-2 mt-5">
                            <button className="py-2 px-3 uppercase rounded-full border-2 text-mainred font-bold bg-[#FFE0BC] border-mainred">
                                Find Mentorship
                            </button>
                            <button className="py-2 px-3 uppercase rounded-full border-2 text-mainred font-bold bg-[#FFE0BC] border-mainred">
                                Become a Mentor
                            </button>
                        </div>
                    </div>
                </section>
            </main>
        </>
    );
}
